name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: { os: [ubuntu-latest, macos-latest] }  # add windows-latest if you want
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake g++ python3 python3-pip
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -j
      - name: Smoke run (synth 20k)
        run: |
          python3 scripts/gen_synth.py --n 20000 --out data/synth_ci.txt
          ./build/orderbook_simulator data/synth_ci.txt \
            --trades-csv data/trades.csv --quotes-csv data/quotes.csv --latency-csv data/latency.csv
      - name: Python checks
        run: |
          python3 -m pip install pandas matplotlib
          python3 scripts/plot_spread_hist.py --no-show || true

